package com.redhat.demo.insurance_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Applicant() {
    }




}